name: Merge valid PRs

on:
  workflow_run:
    workflows: ["Validate PRs"]
    types:
      - completed

jobs:
  approve-and-merge-pr:
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.conclusion == 'success'
    permissions: 
      contents: write
      pull-requests: write
    steps:
      # - name: Get PR info
      #   run: |
      #     PR_INFO=$(gh api \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       "/repos/${{ github.repository }}/pulls" \
      #       --jq '.[] | select(.head.sha=="${{ github.event.workflow_run.head_sha }}")')

      #     if [ -z "$PR_INFO" ]; then
      #       echo "PR not found"
      #       exit 1
      #     fi
          
      #     PR_NUMBER=$(jq -r .number <<< "$PR_INFO")
      #     echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Set PR Number
        run: |
          PR_NUMBER=${{ github.event.workflow_run.pull_requests.number }}
          echo "PR_NUMBER=PR_NUMBER" >> $GITHUB_ENV
          echo "PR number from workflow_run event: $PR_NUMBER"

      - name: Download validation artifact
        uses: actions/download-artifact@v4
        with: 
          name: validation_status
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ vars.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_KEY }}

      - name: approve PR 
        run: |  
          STATUS=$(cat validation_status.txt | tr -d '[:space:]')  

          if [ "$STATUS" != "success" ]; then
            echo "Validation status mismatch: $STATUS"
            exit 1
          fi
          gh pr review --approve $PR_NUMBER
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}

      - name: Merge for approved PRs
        run: gh pr merge --auto --squash $PR_NUMBER
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
