name: Update authorized users

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: main
    paths:
      - 'model-metadata/*'

jobs:
  update-users-list:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
        use-public-rspm: true
        
    - name: Install dependencies
      run: |
        install.packages(c("yaml", "purrr"))
      shell: Rscript {0}
    
    - name: generate users list
      run: |
        Rscript src/code/get_authorized_users.r

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Create a branch
      run: |
        git checkout -b update-authorized-users

    - name: Stage changes
      run: |
        git add src/code/authorized_users.txt

    - name: Commit changes
      run: |
        git commit -m "Update authorized users list"

    - name: Push changes to the repo
      run: |
        git push origin update-authorized-users
  
    - name: Create pull request
      id: create_pr
      run: |
        gh pr create --base main --head update-authorized-users --title "Update authorized users" --body "This PR updates the authorized users list based on the latest metadata."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}