name: Merge Valid PR

on:
  workflow_run:
    workflows: [Hub Submission Validation, Pull Request Labeler]
    types:
      - completed

jobs:
  validate-user-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: dump github context
        run: echo "${{ toJson(github)}}"

      - name: Read authorized user
        id: read_authorized_user
        uses: jaywcjlove/github-action-read-file@main
        with:
          branch: main
          path: 'src/code/authorized_users.txt'

      - name: Get changed files
        id: get_changed_files
        uses: tj-actions/changed-files@v45
        with:
          path: 'model-output'
          dir_names: 'True'

      - name: Approve PR if changes made by authorized user
        run: |
          readarray -t lines_arr <<< "${{ steps.read_authorized_user.outputs.content }}"
          
          for line in "${lines_arr[@]}"; do
            dir=$(echo "$line" | awk '{print $1}')
            user=$(echo "$line" | awk '{print $2}')
            
            for file in ${{ steps.get_changed_files.outputs.all_modified_files }}; do
              if [[ "$file" == "$dir" ]]; then
                if [[ "${{ github.actor }}" == "$user" ]]; then
                  gh pr review --approve "${{ github.event.pull_request.html_url }}"
                  exit 0
                else
                  echo "Error: Only '$user' is allowed to change files in '$dir/'"
                  exit 1
                fi
              fi
            done
          done
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Enable auto-merge for approved PRs
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
